# Generated by Django 4.2.7 on 2023-11-06 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_homework_release_date_alter_homework_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 0, 39, 6, 304342)),
        ),
    ]
